services:
  db-richard-oey:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "gorry"
      MYSQL_USER: "gorry"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "gorry"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1" ]
      timeout: 5s
      retries: 3
  gorry-richard-oey:
    restart: always
    image: gorry-richard-oey
    depends_on:
      db-richard-oey:
        condition: service_healthy
    ports:
      - "9999:9999"
    links:
      - "db-richard-oey:gorry-richard-oey.db"